title: Hey there! I'm Arnau Lacambra
description: > # this means to ignore newlines until "baseurl:"
  Arnau Lacambra Torres website.
  Hey there! If you want to see some cool projects, enter! It's free of Java!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Arnau Lacambra # add your name
author-img: arnau-lacambra.jpg # add your photo
about-author: I am a solutions developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: naulacambra # add your Twitter handle
social-github: naulacambra # add your Github handle
social-linkedin: arnau-lacambra-torres # add your Linkedin handle
social-email: naulacambra@gmail.com # add your Email address

# Disqus
discus-identifier: # mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]